package Utils;

public class Help {

    public static String getHelp() {
        return "<h1>FERRETERIA GALBA - COMANDOS DISPONIBLES</h1>"
                + "<p>Para poder utilizar los comandos, debe enviar un correo a la direccion: <b> grupo@mail.com </b> con el siguiente formato:</p>"
                + "<p> <b> Subject: [COMANDO] [PARAMETROS] </b>, los parametros deben ir entre comillas dobles (\"\") y separados por una coma </p>"
                + "<table style=\" border-collapse: collapse; width: 100%; border: 1px solid black; padding: 8px;\"> \n \n"
                + "<tr> \n \n"
                + "<th style=\"text-align: center; padding: 8px; background-color: #1C7293; color: white; border: 1px solid black;\"> FUNCIONALIDAD </th> \n \n"
                + "<th style=\"text-align: center; padding: 8px; background-color: #1C7293; color: white; border: 1px solid black;\"> COMANDO </th> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Registrar personal</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDUSER [NOMBRE: STRING, CORREO: EMAIL, CONTRASEÑA: STRING, CARGO: STRING, ES PERSONAL: BOOLEAN, ES ADMIN: BOOLEAN]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Registrar cliente</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDCLIENT [NOMBRE: STRING, CONTRASEÑA: STRING, DIRECCION: STRING, TELEFONO: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Ver Perfil</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">SHOWPROFILE []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Actualizar personal</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">EDITUSER [ID: NUMBER, NOMBRE: STRING, CORREO: EMAIL, CONTRASEÑA: STRING, CARGO: STRING, ES PERSONAL: BOOLEAN, ES ADMIN: BOOLEAN]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Actualizar cliente</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">EDITCLIENT [ID: NUMBER, NOMBRE: STRING, CONTRASEÑA: STRING, DIRECCION: STRING, TELEFONO: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar usuario</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELUSER []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar usuarios</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTUSER [] || LISTUSER [KEY: STRING, VALOR: ANY]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Detalles carrito</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTCAR []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Nuevo carrito</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">NEWCAR [] </td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar carrito</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELCAR [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Agregar productos al carrito</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDCARPROD [CANTIDAD: NUMBER, PRODUCTO_ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar productos del carrito</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELCARPROD [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Confirmar Pedido</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">CONFPEDIDO [NIT/CI: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Ver Pedidos</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTPED [] || LISTPED [KEY: STRING, VALOR: ANY]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Ver Un Pedido</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">SHOWPED [ID: NUMBER] </td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Registrar producto</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDPROD [NOMBRE: STRING, IMAGEN: URL, TAMAÑO: STRING, PRECIO: FLOAT, CANTIDAD: INTEGER, DESCRIPCION: STRING, CATEGORIA: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Actualizar producto</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">EDITPROD [ID: NUMBER, NOMBRE: STRING, IMAGEN: URL, TAMAÑO: STRING, PRECIO: FLOAT, DESCRIPCION: STRING, CATEGORIA: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar producto</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELPROD [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar productos</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTPROD [] || LISTUSER [KEY: STRING, VALOR: ANY]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Registrar proveedor</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDPROV [NOMBRE: STRING, EMAIL: STRING, TELEFONO: STRING, DIRECCION: STRING, NIT: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Actualizar proveedor</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">EDITPROV [ID: NUMBER, NOMBRE: STRING, EMAIL: STRING, TELEFONO: STRING, DIRECCION: STRING, NIT: STRING]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar proveedor</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELPROV [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar proveedores</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTPROV [] || LISTUSER [KEY: STRING, VALOR: ANY]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar ingresos</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTING []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Detalles de un ingreso</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DETING [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Nuevo ingreso</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">NEWING [MOTIVO: STRING] </td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar ingreso</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELING [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Agregar productos al ingreso</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDINGPROD [CANTIDAD: NUMBER, INGRESO_ID: NUMBER, PRODUCTO_ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar productos del ingreso</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELINGPROD [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar salidas</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTSAL []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Detalles de una salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DETSAL [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Nueva salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">NEWSAL [MOTIVO: STRING] </td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELSAL [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Agregar productos a la salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDSALPROD [CANTIDAD: NUMBER, INGRESO_ID: NUMBER, PRODUCTO_ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar productos de la salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELSALPROD [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"

                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Listar compras</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">LISTCOM []</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Detalles de una compra</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DETCOM [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Nueva compra</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">NEWCOM [ID_PROVEEDOR: NUMBER] </td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar compra</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELCOM [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Agregar productos a la compra</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">ADDCOMPROD [CANTIDAD: NUMBER, PRECIO: FLOAT, COMPRA_ID: NUMBER, PRODUCTO_ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"
                + "<tr> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">Eliminar productos de la salida</td> \n \n"
                + "<td style=\"text-align: left; padding: 8px; border: 1px solid black;\">DELCOMPROD [ID: NUMBER]</td> \n \n"
                + "</tr> \n \n"

                + "</table>";
    }
}
